### ISSUE TITLE
AFP throws "silent" 500 errors

### ISSUE THREAD

**Issue by range** [ImmobilienScout24/afp-core#3]
When throwing an HTTP 500 error, afp is silent about the reason the error is thrown. This makes it hard to debug problems when needed.

See (internal) PRO-17434

Please find a way to make those errors more verbose, so that clients are able to display a "human readable" error message.

**Comment by snordhausen** [comment]
Errors get logged now. The clients already got feedback about what went wrong, just the server-side log remained empty.
