### ISSUE TITLE
sssd_provider.py only available as example 

### ISSUE THREAD

**Issue by Mortinke** [ImmobilienScout24/afp-core#7]
With regard to the issue #6 I saw the sssd_provider in the examples. Is there any reason why the sssd_provider is only available as example? The sssd_provider fixed the issue #6 for our site. 

I'd be grateful if you could add the sssd_provider as official provider.

**Comment by snordhausen** [comment]
The sssd_provider was left out because for our setup, the grp_provider turned out to be sufficient (and less dependent on the particular technology). Since this fixes a problem for you, I accepted your pull request and will also close #6

**Comment by mikephung** [comment]
thanks Mortinke for the great fix + PR, and also thanks snordhausen for the merge

**Comment by snordhausen** [comment]
I had to tweak it a bit, though, to get past all the CI tools. See 35588ac, but this should not break anything for you.
